# Generated by Django 3.1.4 on 2021-04-26 05:36

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='template_photo.JPG', upload_to='profile_pics')),
                ('name', models.CharField(default='', max_length=255)),
                ('occupation', models.CharField(default='', max_length=255)),
                ('about_Me', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='personal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('residency', models.CharField(default='', max_length=255)),
                ('languages', models.CharField(help_text='Enter Comma Seperated Values', max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.person')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_detail', models.CharField(default='', max_length=255)),
                ('extra_title', models.CharField(default='', max_length=255)),
                ('extra_subtitle', models.CharField(default='', max_length=255)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('extra_description', models.TextField(default='')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.person')),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=255)),
                ('stamp', models.ImageField(default='template_signature.png', upload_to='stamp')),
                ('recepient', models.CharField(default='', max_length=255)),
                ('formulation', models.CharField(default='', max_length=255)),
                ('text', models.TextField(default='')),
                ('date', models.DateField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.person')),
            ],
        ),
        migrations.CreateModel(
            name='Experience3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_detail3', models.CharField(default='', max_length=255)),
                ('company3', models.CharField(default='', max_length=255)),
                ('job_title3', models.CharField(default='', max_length=255)),
                ('start_Date3', models.DateField(blank=True, null=True)),
                ('end_Date3', models.DateField(blank=True, null=True)),
                ('job_description3', models.TextField(default='')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.person')),
            ],
        ),
        migrations.CreateModel(
            name='Experience2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_detail2', models.CharField(default='', max_length=255)),
                ('company2', models.CharField(default='', max_length=255)),
                ('job_title2', models.CharField(default='', max_length=255)),
                ('start_Date2', models.DateField(blank=True, null=True)),
                ('end_Date2', models.DateField(blank=True, null=True)),
                ('job_description2', models.TextField(default='')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.person')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_detail', models.CharField(default='', max_length=255)),
                ('company', models.CharField(default='', max_length=255)),
                ('job_title', models.CharField(default='', max_length=255)),
                ('start_Date', models.DateField(blank=True, null=True)),
                ('end_Date', models.DateField(blank=True, null=True)),
                ('job_description', models.TextField(default='')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.person')),
            ],
        ),
        migrations.CreateModel(
            name='Education3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail3', models.CharField(default='', max_length=255)),
                ('institution3', models.CharField(default='', max_length=255)),
                ('level3', models.CharField(default='', max_length=255)),
                ('start_date3', models.DateField(blank=True, null=True)),
                ('end_date3', models.DateField(blank=True, null=True)),
                ('description3', models.TextField(default='')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.person')),
            ],
        ),
        migrations.CreateModel(
            name='Education2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail2', models.CharField(default='', max_length=255)),
                ('institution2', models.CharField(default='', max_length=255)),
                ('level2', models.CharField(default='', max_length=255)),
                ('start_date2', models.DateField(blank=True, null=True)),
                ('end_date2', models.DateField(blank=True, null=True)),
                ('description2', models.TextField(default='')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.person')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(default='', max_length=255)),
                ('institution', models.CharField(default='', max_length=255)),
                ('level', models.CharField(default='', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(default='')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.person')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=150)),
                ('address', models.TextField(default='', max_length=2000)),
                ('phone', models.CharField(default='', max_length=255)),
                ('website', models.URLField(default='', max_length=250)),
                ('person', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='resume.person')),
            ],
        ),
    ]
